Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,18 +25,27 @@ jobs:
 
       - name: Build
         run: npm run build
+
       - name: Debug
         run: |
           echo "Bucket: ${{ secrets.AWS_S3_BUCKET }}"
           echo "CF ID: ${{ secrets.AWS_CF_ID }}"
           echo "Bucket: ${{ secrets.ACCESS_KEY_ID }}"
           echo "CF ID: ${{ secrets.SECRET_ACCESS_KEY }}"
+
       - name: Deploy
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
         run: |
           echo "AWS s3 sync"
-          aws s3 sync --region ap-northeast-1 ./out s3://${{ secrets.AWS_S3_BUCKET}} --delete
+          # ビルドされたファイルが ./out ディレクトリにあることを確認
+          if [ -d "./out" ]; then
+            aws s3 sync --region ap-northeast-1 ./out s3://${{ secrets.AWS_S3_BUCKET }} --delete
+          else
+            echo "Error: The ./out directory does not exist."
+            exit 1
+          fi
+          
           echo "AWS CF reset"
           aws cloudfront create-invalidation --region ap-northeast-1 --distribution-id ${{ secrets.AWS_CF_ID }} --paths "/*"
